// -------------------------------------------------------------
// 
// File Name: D:\Project\FPGA_XC7A200T\learning\study_l1_speed_pi_hdl_compare\.runtime\b_fresh_final_02\generated\speed_pi_hdl\HDLCore.sv
// Created: 2026-10-04 17:18:43
// 
// Generated by MATLAB 26.2, HDL Coder 26.2, and Simulink 26.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.0001
// Target subsystem base rate: 0.0001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// iq_ref_A                      ce_out        0.0001
// iq_unlimited_A                ce_out        0.0001
// integrator_A                  ce_out        0.0001
// saturation_active             ce_out        0.0001
// integrator_next_A             ce_out        0.0001
// previous_excess_A             ce_out        0.0001
// excess_next_A                 ce_out        0.0001
// hard_reset                    ce_out        0.0001
// int_reset                     ce_out        0.0001
// iq_limited_A                  ce_out        0.0001
// error_mmps                    ce_out        0.0001
// P_A                           ce_out        0.0001
// KiTs_A                        ce_out        0.0001
// AW_A                          ce_out        0.0001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HDLCore
// Source Path: speed_pi_hdl/HDLCore
// Hierarchy Level: 0
// Model version: 1.2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HDLCore
          (  input logic clk,
             input logic init_reset,
             input logic clk_enable,
             input logic signed [31:0] v_ref_mmps  /* sfix32_En20 */,
             input logic signed [31:0] v_meas_mmps  /* sfix32_En20 */,
             input logic enable,
             input logic pi_reset,
             input logic sample_tick,
             input logic angle_init,
             input logic test_mode,
             output logic ce_out,
             output logic signed [24:0] iq_ref_A  /* sfix25_En15 */,
             output logic signed [41:0] iq_unlimited_A  /* sfix42_En30 */,
             output logic signed [31:0] integrator_A  /* sfix32_En30 */,
             output logic saturation_active,
             output logic signed [31:0] integrator_next_A  /* sfix32_En30 */,
             output logic signed [39:0] previous_excess_A  /* sfix40_En30 */,
             output logic signed [39:0] excess_next_A  /* sfix40_En30 */,
             output logic hard_reset,
             output logic int_reset,
             output logic signed [41:0] iq_limited_A  /* sfix42_En30 */,
             output logic signed [32:0] error_mmps  /* sfix33_En20 */,
             output logic signed [39:0] P_A  /* sfix40_En30 */,
             output logic signed [39:0] KiTs_A  /* sfix40_En30 */,
             output logic signed [39:0] AW_A  /* sfix40_En30 */);


  logic enb;
  logic signed [31:0] v_ref_mmps_1;  /* sfix32_En20 */
  logic signed [31:0] v_meas_mmps_1;  /* sfix32_En20 */
  logic enable_1;
  logic pi_reset_1;
  logic angle_init_1;
  logic test_mode_1;
  logic sample_tick_1;
  logic signed [24:0] PI_iq_ref_A;  /* sfix25_En15 */
  logic signed [41:0] PI_iq_unlimited_A;  /* sfix42_En30 */
  logic signed [31:0] PI_integrator_A;  /* sfix32_En30 */
  logic PI_saturation_active;
  logic signed [31:0] PI_integrator_next_A;  /* sfix32_En30 */
  logic signed [39:0] PI_previous_excess_A;  /* sfix40_En30 */
  logic signed [39:0] PI_excess_next_A;  /* sfix40_En30 */
  logic PI_hard_reset;
  logic PI_int_reset;
  logic signed [41:0] PI_iq_limited_A;  /* sfix42_En30 */
  logic signed [32:0] PI_error_mmps;  /* sfix33_En20 */
  logic signed [39:0] PI_P_A;  /* sfix40_En30 */
  logic signed [39:0] PI_KiTs_A;  /* sfix40_En30 */
  logic signed [39:0] PI_AW_A;  /* sfix40_En30 */


  assign enb = clk_enable;

  always_ff @(posedge clk)
    begin : in_0_pipe_process
      if (init_reset == 1'b1) begin
        v_ref_mmps_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          v_ref_mmps_1 <= v_ref_mmps;
        end
      end
    end

  always_ff @(posedge clk)
    begin : in_1_pipe_process
      if (init_reset == 1'b1) begin
        v_meas_mmps_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          v_meas_mmps_1 <= v_meas_mmps;
        end
      end
    end

  always_ff @(posedge clk)
    begin : in_2_pipe_process
      if (init_reset == 1'b1) begin
        enable_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          enable_1 <= enable;
        end
      end
    end

  always_ff @(posedge clk)
    begin : in_3_pipe_process
      if (init_reset == 1'b1) begin
        pi_reset_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          pi_reset_1 <= pi_reset;
        end
      end
    end

  always_ff @(posedge clk)
    begin : in_5_pipe_process
      if (init_reset == 1'b1) begin
        angle_init_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          angle_init_1 <= angle_init;
        end
      end
    end

  always_ff @(posedge clk)
    begin : in_6_pipe_process
      if (init_reset == 1'b1) begin
        test_mode_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          test_mode_1 <= test_mode;
        end
      end
    end

  always_ff @(posedge clk)
    begin : in_4_pipe_process
      if (init_reset == 1'b1) begin
        sample_tick_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          sample_tick_1 <= sample_tick;
        end
      end
    end

  PI u_PI (.clk(clk),
           .init_reset(init_reset),
           .enb(clk_enable),
           .v_ref_mmps(v_ref_mmps_1),  /* sfix32_En20 */
           .v_meas_mmps(v_meas_mmps_1),  /* sfix32_En20 */
           .enable(enable_1),
           .reset(pi_reset_1),
           .angle_init(angle_init_1),
           .test_mode(test_mode_1),
           .Tick(sample_tick_1),
           .iq_ref_A(PI_iq_ref_A),  /* sfix25_En15 */
           .iq_unlimited_A(PI_iq_unlimited_A),  /* sfix42_En30 */
           .integrator_A(PI_integrator_A),  /* sfix32_En30 */
           .saturation_active(PI_saturation_active),
           .integrator_next_A(PI_integrator_next_A),  /* sfix32_En30 */
           .previous_excess_A(PI_previous_excess_A),  /* sfix40_En30 */
           .excess_next_A(PI_excess_next_A),  /* sfix40_En30 */
           .hard_reset(PI_hard_reset),
           .int_reset(PI_int_reset),
           .iq_limited_A(PI_iq_limited_A),  /* sfix42_En30 */
           .error_mmps(PI_error_mmps),  /* sfix33_En20 */
           .P_A(PI_P_A),  /* sfix40_En30 */
           .KiTs_A(PI_KiTs_A),  /* sfix40_En30 */
           .AW_A(PI_AW_A)  /* sfix40_En30 */
           );
  assign iq_ref_A = PI_iq_ref_A;

  assign iq_unlimited_A = PI_iq_unlimited_A;

  assign integrator_A = PI_integrator_A;

  assign saturation_active = PI_saturation_active;

  assign integrator_next_A = PI_integrator_next_A;

  assign previous_excess_A = PI_previous_excess_A;

  assign excess_next_A = PI_excess_next_A;

  assign hard_reset = PI_hard_reset;

  assign int_reset = PI_int_reset;

  assign iq_limited_A = PI_iq_limited_A;

  assign error_mmps = PI_error_mmps;

  assign P_A = PI_P_A;

  assign KiTs_A = PI_KiTs_A;

  assign AW_A = PI_AW_A;

  assign ce_out = clk_enable;

endmodule  // HDLCore

