function metrics=study_l1_d_validate(r,reportDir)
% Validate a real Study-L1 D run; no model changes or waveform time shifts.
% r keeps the existing step7d_run_scenario schema, with r.speed_pi containing:
% implementation, latency_s, input_event_time_s, physical_result_event_time_s,
% result_event_time_s (observed), iq_ref_time_s/iq_ref_A (raw PI held output),
% result_count_time_s/result_count (observed cumulative completion count).
assert(isfolder(reportDir),'StudyL1D:ReportDir','Run directory must exist.');
file=fullfile(reportDir,'case_metrics.json');
assert(~isfile(file),'StudyL1D:ExistingEvidence','Never overwrite case evidence.');
assert(isfield(r,'speed_pi'),'StudyL1D:MissingSpeedEvidence','Missing live speed PI evidence.');
s=r.speed_pi;
required={'implementation','latency_s','input_event_time_s','physical_result_event_time_s', ...
 'result_event_time_s','iq_ref_time_s','iq_ref_A','result_count_time_s','result_count'};
for k=1:numel(required)
 assert(isfield(s,required{k}),'StudyL1D:MissingSpeedEvidence','Missing speed_pi.%s',required{k});
end
assert(any(strcmp(s.implementation,{'original','coder_baseline','hand_sv'})), ...
 'StudyL1D:Implementation','Unknown speed implementation.');
assert(r.cfg.backend==1 && r.effective_config.CONTROL_BACKEND==1, ...
 'StudyL1D:Backend','All cases must use the same handwritten FOC backend.');
% The repository evaluator is authoritative for the frozen Step7D speed gates.
acceptance=step7d_assert_result(r,r.cfg);
tol=1e-12; dt=r.cfg.commTs;
assert(abs(dt-1e-6)<tol,'StudyL1D:CommunicationStep','D uses the existing 1 us system step.');
latency=double(s.latency_s);
if strcmp(s.implementation,'original')
 assert(isfinite(latency) && abs(latency)<tol,'StudyL1D:Latency','Original speed PI has no RTL pipeline latency.');
else
 % The frozen two-edge boundary gives one clock from acceptance to result.
 % Launch-to-acceptance phase is measured by the runtime, not forced to 20 ns.
 assert(isfinite(latency) && latency>20e-9 && latency<=40e-9+tol, ...
  'StudyL1D:Latency','RTL source-to-result latency must contain the measured capture phase plus one clock.');
 assert(isfield(s,'launch_cycle') && isfield(s,'result_cycle') && all(s.result_cycle-s.launch_cycle==1), ...
  'StudyL1D:Latency','Actual input acceptance to completion must remain one 50 MHz clock.');
end
expected=(.0009:.001:r.cfg.stopTime)';
launch=column(s.input_event_time_s); physical=column(s.physical_result_event_time_s);
observed=column(s.result_event_time_s);
assert(numel(launch)==numel(expected) && numel(physical)==numel(expected) && numel(observed)==numel(expected), ...
 'StudyL1D:SpeedCoverage','Speed launches/completions do not cover the whole run.');
assert(all(abs(launch-expected)<tol) && all(abs(physical-launch-latency)<tol), ...
 'StudyL1D:SpeedPhase','Wrong first phase, 1 ms update interval, or measured physical latency.');
observationDelay=observed-physical;
assert(all(observationDelay>=-tol & observationDelay<=dt+tol), ...
 'StudyL1D:ResultObservation','Observed completion must follow physical completion within one communication step.');
ct=column(s.result_count_time_s); count=column(s.result_count);
it=column(s.iq_ref_time_s); iq=column(s.iq_ref_A);
assert(numel(ct)==numel(count) && numel(it)==numel(iq) && numel(ct)>1 && numel(it)>1, ...
 'StudyL1D:SignalDimensions','Invalid count or held PI output dimensions.');
assert(all(diff(ct)>0) && all(diff(it)>0) && abs(ct(1))<tol && abs(it(1))<tol && ...
 abs(ct(end)-r.cfg.stopTime)<tol && abs(it(end)-r.cfg.stopTime)<tol, ...
 'StudyL1D:SignalCoverage','Count and held output must include the complete run.');
assert(all(count>=0 & count==fix(count)) && count(1)==0 && count(end)==numel(expected), ...
 'StudyL1D:ResultCount','Invalid initial/final completion count.');
increments=diff(count);
assert(all(increments==0 | increments==1),'StudyL1D:ResultCount','Lost, repeated, or reversed completion count.');
ci=find(increments==1)+1; countEvents=ct(ci);
assert(numel(ci)==numel(observed) && all(abs(countEvents-observed)<tol), ...
 'StudyL1D:ResultCount','Event timestamps do not come from observed count increments.');
% Same-time communication observations are required. This makes the hold
% gate independent of an inferred future event or arbitrary time shifting.
assert(isequal(ct,it),'StudyL1D:HoldGrid','Count and raw held PI output must share their real observation grid.');
changes=find(diff(iq)~=0)+1;
assert(all(ismember(changes,ci)),'StudyL1D:HoldViolation','Raw PI output changed without a new completed result.');
assert(all(iq(it<observed(1)-tol)==0),'StudyL1D:InitialHold','Initial held output must be zero.');
assert(max(abs(iq))<=1+tol,'StudyL1D:SpeedCurrentLimit','Speed PI exceeded the frozen output limit.');
prefix=struct;
if strcmp(r.cfg.name,'convergence_prefix')
 % A short chain sanity gate; no claim of full-position settling acceptance.
 direction=sign(r.cfg.host.Host_Target_mm);
 assert(direction~=0,'StudyL1D:PositionTarget','Position prefix target must be nonzero.');
 active=r.time_s>=r.cfg.host.Host_Start_s;
 prefix=struct('target_mm',r.cfg.host.Host_Target_mm, ...
  'position_reference_span_mm',max(r.x_ref_mm)-min(r.x_ref_mm), ...
  'speed_reference_span_mmps',max(r.v_ref_mmps)-min(r.v_ref_mmps), ...
  'maximum_target_direction_speed_mmps',max(direction*r.v_mmps(active)), ...
  'maximum_target_direction_position_mm',max(direction*r.x_mm(active)), ...
  'iq_peak_A',r.peaks.iq_A,'id_peak_A',r.peaks.id_A, ...
  'iq_ref_peak_A',r.peaks.iq_ref_A);
 assert(prefix.position_reference_span_mm>0 && prefix.speed_reference_span_mmps>0 && ...
  prefix.maximum_target_direction_speed_mmps>0 && prefix.maximum_target_direction_position_mm>0, ...
  'StudyL1D:PositionChain','Position prefix did not exercise the Host/Position/speed/current/plant chain.');
 assert(r.peaks.iq_A<=1.5 && r.peaks.iq_ref_A<=1+tol && r.peaks.id_A<=r.cfg.thresholds.idMax, ...
  'StudyL1D:PositionCurrentPeak','Position prefix current is abnormal.');
 prefix.full_position_settling_claim=false;
end
metrics=struct('schema','study_l1_checkpoint_d_case_v1','implementation',s.implementation, ...
 'scenario',r.cfg.name,'cfg',r.cfg,'effective_config',r.effective_config, ...
 'step7d_acceptance',acceptance,'peaks',r.peaks,'position_prefix',prefix, ...
 'speed_launch_count',numel(launch),'speed_result_count',numel(physical), ...
 'speed_first_launch_s',launch(1),'speed_update_interval_s',.001, ...
 'physical_latency_s',latency,'maximum_observation_delay_s',max(observationDelay), ...
 'held_output_change_count',numel(changes),'hold_gate_pass',true, ...
 'foc_accepted_count',numel(r.command_events.accepted_id), ...
 'foc_active_count',numel(r.command_events.active_id), ...
 'foc_accepted_first_s',r.command_events.accepted_time_s(1), ...
 'foc_active_first_s',r.command_events.active_time_s(1), ...
 'foc_transaction_interval_s',1e-4,'foc_accepted_to_active_s',50e-6, ...
 'fault_code_max',max(r.fault_code),'needs_reset_max',max(r.needs_reset), ...
 'gate_pass',true,'hand_sv_50mhz_setup_pass',false, ...
 'hand_sv_frozen_wns_ns',-1.957);
if isfield(s,'physical_timestamp_basis'), metrics.physical_timestamp_basis=s.physical_timestamp_basis; end
if isfield(s,'clock_evidence'), metrics.clock_evidence=s.clock_evidence; end
if isfield(s,'managed_reference_events'), metrics.managed_reference_events=s.managed_reference_events; end
f=fopen(file,'w'); assert(f>=0,'StudyL1D:ReportWrite','Cannot open case evidence.');
c=onCleanup(@()fclose(f)); %#ok<NASGU>
fprintf(f,'%s\n',jsonencode(metrics,'PrettyPrint',true));
fprintf('STUDY_L1_D_CASE_GATE_PASS %s %s events=%d physical_latency_ns=%.8g\n', ...
 r.cfg.name,s.implementation,numel(physical),latency*1e9);
end
function x=column(x)
x=double(x(:));
assert(all(isfinite(x)),'StudyL1D:NonFiniteSpeedEvidence','Nonfinite speed evidence.');
end
