// -------------------------------------------------------------
// 
// File Name: D:\Project\FPGA_XC7A200T\learning\study_l1_speed_pi_hdl_compare\.runtime\c_csd_02\generated\speed_pi_hdl\PI.sv
// Created: 2026-10-04 18:26:07
// 
// Generated by MATLAB 26.2, HDL Coder 26.2, and Simulink 26.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PI
// Source Path: speed_pi_hdl/HDLCore/PI
// Hierarchy Level: 1
// Model version: 1.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PI
          (  input logic clk,
             input logic init_reset,
             input logic enb,
             input logic signed [31:0] v_ref_mmps  /* sfix32_En20 */,
             input logic signed [31:0] v_meas_mmps  /* sfix32_En20 */,
             input logic enable,
             input logic reset,
             input logic angle_init,
             input logic test_mode,
             input logic Tick,
             output logic signed [24:0] iq_ref_A  /* sfix25_En15 */,
             output logic signed [41:0] iq_unlimited_A  /* sfix42_En30 */,
             output logic signed [31:0] integrator_A  /* sfix32_En30 */,
             output logic saturation_active,
             output logic signed [31:0] integrator_next_A  /* sfix32_En30 */,
             output logic signed [39:0] previous_excess_A  /* sfix40_En30 */,
             output logic signed [39:0] excess_next_A  /* sfix40_En30 */,
             output logic hard_reset,
             output logic int_reset,
             output logic signed [41:0] iq_limited_A  /* sfix42_En30 */,
             output logic signed [32:0] error_mmps  /* sfix33_En20 */,
             output logic signed [39:0] P_A  /* sfix40_En30 */,
             output logic signed [39:0] KiTs_A  /* sfix40_En30 */,
             output logic signed [39:0] AW_A  /* sfix40_En30 */);


  logic enb_gated;
  logic Disabled_out1;
  logic Hard_out1;
  logic signed [32:0] Error_sub_cast;  /* sfix33_En20 */
  logic signed [32:0] Error_sub_cast_1;  /* sfix33_En20 */
  logic signed [32:0] Error_out1;  /* sfix33_En20 */
  logic signed [65:0] P_mul_temp;  /* sfix66_En50 */
  logic signed [64:0] P_cast;  /* sfix65_En50 */
  logic signed [39:0] P_out1;  /* sfix40_En30 */
  logic signed [32:0] AbsRef_y;  /* sfix33_En20 */
  logic signed [32:0] AbsRef_cast;  /* sfix33_En20 */
  logic signed [31:0] AbsRef_out1;  /* sfix32_En20 */
  logic signed [31:0] ZeroEps_out1;  /* sfix32_En20 */
  logic RefZero_out1;
  logic signed [31:0] FFEps_out1;  /* sfix32_En20 */
  logic signed [31:0] RefSign_out1;  /* int32 */
  logic signed [64:0] SignedError_mul_temp;  /* sfix65_En20 */
  logic signed [32:0] SignedError_out1;  /* sfix33_En20 */
  logic RefMoving_out1;
  logic signed [32:0] OverEps_out1;  /* sfix33_En20 */
  logic OverSpeed_out1;
  logic Over_out1;
  logic Int_out1;
  logic signed [65:0] KiTs_mul_temp;  /* sfix66_En50 */
  logic signed [64:0] KiTs_cast;  /* sfix65_En50 */
  logic signed [39:0] KiTs_out1;  /* sfix40_En30 */
  logic Tick_delayed;
  logic signed [43:0] UpperLimit_out;  /* sfix44_En30 */
  logic signed [43:0] LowerLimit_out;  /* sfix44_En30 */
  logic signed [31:0] StateZero_out1;  /* sfix32_En30 */
  logic signed [41:0] UpperLimit_out_1;  /* sfix42_En30 */
  logic signed [41:0] LowerLimit_out_1;  /* sfix42_En30 */
  logic signed [41:0] Unlimited_out1;  /* sfix42_En30 */
  logic Sat_LowerRelOp_out;
  logic signed [41:0] Sat_LowerSwitch_out;  /* sfix42_En30 */
  logic signed [43:0] Update_out1;  /* sfix44_En30 */
  logic Sat_LowerRelOp_out_1;
  logic signed [43:0] Sat_LowerSwitch_out_1;  /* sfix44_En30 */
  logic signed [41:0] OutputLimit_out1;  /* sfix42_En30 */
  logic signed [43:0] Excess_sub_cast;  /* sfix44_En30 */
  logic signed [43:0] Excess_sub_cast_1;  /* sfix44_En30 */
  logic signed [43:0] Excess_sub_temp;  /* sfix44_En30 */
  logic signed [39:0] Excess_out1;  /* sfix40_En30 */
  logic signed [39:0] PreviousExcess_out1;  /* sfix40_En30 */
  logic signed [72:0] AW_mul_temp;  /* sfix73_En60 */
  logic signed [71:0] AW_cast;  /* sfix72_En60 */
  logic signed [39:0] AW_out1;  /* sfix40_En30 */
  logic signed [31:0] Integrator_out1;  /* sfix32_En30 */
  logic signed [43:0] Update_stage2_add_cast;  /* sfix44_En30 */
  logic signed [43:0] Update_stage2_add_cast_1;  /* sfix44_En30 */
  logic signed [43:0] Update_op_stage1;  /* sfix44_En30 */
  logic signed [44:0] Update_stage3_sub_cast;  /* sfix45_En30 */
  logic signed [43:0] Update_stage3_sub_cast_1;  /* sfix44_En30 */
  logic signed [44:0] Update_stage3_sub_cast_2;  /* sfix45_En30 */
  logic signed [44:0] Update_stage3_sub_temp;  /* sfix45_En30 */
  logic Sat_UpperRelOp_out;
  logic signed [43:0] IntegratorLimit_out1;  /* sfix44_En30 */
  logic signed [31:0] StateFormat_out1;  /* sfix32_En30 */
  logic signed [31:0] IntReset_out1;  /* sfix32_En30 */
  logic signed [43:0] Unlimited_add_cast;  /* sfix44_En30 */
  logic signed [43:0] Unlimited_add_cast_1;  /* sfix44_En30 */
  logic signed [43:0] Unlimited_add_temp;  /* sfix44_En30 */
  logic Sat_UpperRelOp_out_1;
  logic signed [24:0] OutputFormat_out1;  /* sfix25_En15 */
  logic signed [24:0] OutputZero_out1;  /* sfix25_En15 */
  logic signed [24:0] HardReset_out1;  /* sfix25_En15 */
  logic signed [24:0] HardReset_out1_hold;  /* sfix25_En15 */
  logic signed [41:0] Unlimited_out1_hold;  /* sfix42_En30 */
  logic signed [31:0] Integrator_out1_hold;  /* sfix32_En30 */
  logic Saturated_out1;
  logic Saturated_out1_hold;
  logic signed [31:0] IntReset_out1_hold;  /* sfix32_En30 */
  logic signed [39:0] PreviousExcess_out1_hold;  /* sfix40_En30 */
  logic signed [39:0] Excess_out1_hold;  /* sfix40_En30 */
  logic Hard_out1_hold;
  logic Int_out1_hold;
  logic signed [41:0] OutputLimit_out1_hold;  /* sfix42_En30 */
  logic signed [32:0] Error_out1_hold;  /* sfix33_En20 */
  logic signed [39:0] P_out1_hold;  /* sfix40_En30 */
  logic signed [39:0] KiTs_out1_hold;  /* sfix40_En30 */
  logic signed [39:0] AW_out1_hold;  /* sfix40_En30 */


  assign Disabled_out1 =  ~ enable;
  assign Hard_out1 = Disabled_out1 | (test_mode | (angle_init | reset));
  assign Error_sub_cast = {v_ref_mmps[31], v_ref_mmps};
  assign Error_sub_cast_1 = {v_meas_mmps[31], v_meas_mmps};
  assign Error_out1 = Error_sub_cast - Error_sub_cast_1;
  assign P_mul_temp = 33'sh0012775E0 * Error_out1;
  assign P_cast = P_mul_temp[64:0];
  assign P_out1 = (((P_cast[64] == 1'b0) && (P_cast[63:59] != 5'b00000)) || ((P_cast[64] == 1'b0) && (P_cast[59:20] == 40'sh7FFFFFFFFF)) ? 40'sh7FFFFFFFFF :
              ((P_cast[64] == 1'b1) && (P_cast[63:59] != 5'b11111) ? 40'sh8000000000 :
              $signed(P_cast[59:20]) + $signed({1'b0, P_cast[19] & (P_cast[20] | (|P_cast[18:0]))})));
  assign AbsRef_cast = {v_ref_mmps[31], v_ref_mmps};
  assign AbsRef_y = (v_ref_mmps < 32'sb00000000000000000000000000000000 ?  - (AbsRef_cast) :
              {v_ref_mmps[31], v_ref_mmps});
  assign AbsRef_out1 = ((AbsRef_y[32] == 1'b0) && (AbsRef_y[31] != 1'b0) ? 32'sb01111111111111111111111111111111 :
              ((AbsRef_y[32] == 1'b1) && (AbsRef_y[31] != 1'b1) ? 32'sb10000000000000000000000000000000 :
              $signed(AbsRef_y[31:0])));
  assign ZeroEps_out1 = 32'sb00000000000000000000000000000000;
  assign RefZero_out1 = AbsRef_out1 < ZeroEps_out1;
  assign FFEps_out1 = 32'sb00000000000010000000000000000000;
  assign RefSign_out1 = (v_ref_mmps > 32'sb00000000000000000000000000000000 ? 32'sb00000000000000000000000000000001 :
              (v_ref_mmps < 32'sb00000000000000000000000000000000 ? 32'sb11111111111111111111111111111111 :
              32'sb00000000000000000000000000000000));
  assign SignedError_mul_temp = RefSign_out1 * Error_out1;
  assign SignedError_out1 = ((SignedError_mul_temp[64] == 1'b0) && (SignedError_mul_temp[63:32] != 32'b00000000000000000000000000000000) ? 33'sh0FFFFFFFF :
              ((SignedError_mul_temp[64] == 1'b1) && (SignedError_mul_temp[63:32] != 32'b11111111111111111111111111111111) ? 33'sh100000000 :
              $signed(SignedError_mul_temp[32:0])));
  assign RefMoving_out1 = AbsRef_out1 > FFEps_out1;
  assign OverEps_out1 = 33'sh1FFD00000;
  assign OverSpeed_out1 = SignedError_out1 < OverEps_out1;
  assign Over_out1 = RefMoving_out1 & OverSpeed_out1;
  assign Int_out1 = Over_out1 | (Hard_out1 | RefZero_out1);
  assign KiTs_mul_temp = 33'sh00017A308 * Error_out1;
  assign KiTs_cast = KiTs_mul_temp[64:0];
  assign KiTs_out1 = (((KiTs_cast[64] == 1'b0) && (KiTs_cast[63:59] != 5'b00000)) || ((KiTs_cast[64] == 1'b0) && (KiTs_cast[59:20] == 40'sh7FFFFFFFFF)) ? 40'sh7FFFFFFFFF :
              ((KiTs_cast[64] == 1'b1) && (KiTs_cast[63:59] != 5'b11111) ? 40'sh8000000000 :
              $signed(KiTs_cast[59:20]) + $signed({1'b0, KiTs_cast[19] & (KiTs_cast[20] | (|KiTs_cast[18:0]))})));
  always @(posedge clk)
    begin : Tick_delay
      if (init_reset) begin
        Tick_delayed <= 1'b1;
      end
      else begin
        if (enb) begin
          Tick_delayed <= Tick;
        end
      end
    end

  assign enb_gated = !Tick_delayed && Tick && enb;

  assign UpperLimit_out = 44'sh00020000000;

  assign LowerLimit_out = 44'shFFFE0000000;

  assign StateZero_out1 = 32'sb00000000000000000000000000000000;
  assign UpperLimit_out_1 = 42'sh00040000000;

  assign LowerLimit_out_1 = 42'sh3FFC0000000;

  assign Sat_LowerRelOp_out = Unlimited_out1 < LowerLimit_out_1;

  assign Sat_LowerSwitch_out = (Sat_LowerRelOp_out == 1'b0 ? Unlimited_out1 :
              LowerLimit_out_1);

  assign Sat_LowerRelOp_out_1 = Update_out1 < LowerLimit_out;

  assign Sat_LowerSwitch_out_1 = (Sat_LowerRelOp_out_1 == 1'b0 ? Update_out1 :
              LowerLimit_out);

  assign Excess_sub_cast = {{2{Unlimited_out1[41]}}, Unlimited_out1};
  assign Excess_sub_cast_1 = {{2{OutputLimit_out1[41]}}, OutputLimit_out1};
  assign Excess_sub_temp = Excess_sub_cast - Excess_sub_cast_1;
  assign Excess_out1 = ((Excess_sub_temp[43] == 1'b0) && (Excess_sub_temp[42:39] != 4'b0000) ? 40'sh7FFFFFFFFF :
              ((Excess_sub_temp[43] == 1'b1) && (Excess_sub_temp[42:39] != 4'b1111) ? 40'sh8000000000 :
              $signed(Excess_sub_temp[39:0])));
  always_ff @(posedge clk)
    begin : PreviousExcess_process
      if (init_reset == 1'b1) begin
        PreviousExcess_out1 <= 40'sh0000000000;
      end
      else begin
        if (enb_gated) begin
          PreviousExcess_out1 <= Excess_out1;
        end
      end
    end
  // CSD Encoding (85899346) : 010100100001'01'001'00001010010; Cost (Adders) = 8
  assign AW_mul_temp = ((((((($signed({PreviousExcess_out1, 26'b00000000000000000000000000}) + $signed({PreviousExcess_out1, 24'b000000000000000000000000})) + $signed({PreviousExcess_out1, 21'b000000000000000000000})) - $signed({PreviousExcess_out1, 16'b0000000000000000})) - $signed({PreviousExcess_out1, 14'b00000000000000})) - $signed({PreviousExcess_out1, 11'b00000000000})) + $signed({PreviousExcess_out1, 6'b000000})) + $signed({PreviousExcess_out1, 4'b0000})) + $signed({PreviousExcess_out1, 1'b0});
  assign AW_cast = AW_mul_temp[71:0];
  assign AW_out1 = (((AW_cast[71] == 1'b0) && (AW_cast[70:69] != 2'b00)) || ((AW_cast[71] == 1'b0) && (AW_cast[69:30] == 40'sh7FFFFFFFFF)) ? 40'sh7FFFFFFFFF :
              ((AW_cast[71] == 1'b1) && (AW_cast[70:69] != 2'b11) ? 40'sh8000000000 :
              $signed(AW_cast[69:30]) + $signed({1'b0, AW_cast[29] & (AW_cast[30] | (|AW_cast[28:0]))})));
  assign Update_stage2_add_cast = {{12{Integrator_out1[31]}}, Integrator_out1};
  assign Update_stage2_add_cast_1 = {{4{KiTs_out1[39]}}, KiTs_out1};
  assign Update_op_stage1 = Update_stage2_add_cast + Update_stage2_add_cast_1;

  assign Update_stage3_sub_cast = {Update_op_stage1[43], Update_op_stage1};
  assign Update_stage3_sub_cast_1 = {{4{AW_out1[39]}}, AW_out1};
  assign Update_stage3_sub_cast_2 = {Update_stage3_sub_cast_1[43], Update_stage3_sub_cast_1};
  assign Update_stage3_sub_temp = Update_stage3_sub_cast - Update_stage3_sub_cast_2;
  assign Update_out1 = ((Update_stage3_sub_temp[44] == 1'b0) && (Update_stage3_sub_temp[43] != 1'b0) ? 44'sh7FFFFFFFFFF :
              ((Update_stage3_sub_temp[44] == 1'b1) && (Update_stage3_sub_temp[43] != 1'b1) ? 44'sh80000000000 :
              $signed(Update_stage3_sub_temp[43:0])));
  assign Sat_UpperRelOp_out = Update_out1 > UpperLimit_out;

  assign IntegratorLimit_out1 = (Sat_UpperRelOp_out == 1'b0 ? Sat_LowerSwitch_out_1 :
              UpperLimit_out);

  assign StateFormat_out1 = ((IntegratorLimit_out1[43] == 1'b0) && (IntegratorLimit_out1[42:31] != 12'b000000000000) ? 32'sb01111111111111111111111111111111 :
              ((IntegratorLimit_out1[43] == 1'b1) && (IntegratorLimit_out1[42:31] != 12'b111111111111) ? 32'sb10000000000000000000000000000000 :
              $signed(IntegratorLimit_out1[31:0])));
  assign IntReset_out1 = (Int_out1 == 1'b0 ? StateFormat_out1 :
              StateZero_out1);
  always_ff @(posedge clk)
    begin : Integrator_process
      if (init_reset == 1'b1) begin
        Integrator_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_gated) begin
          Integrator_out1 <= IntReset_out1;
        end
      end
    end
  assign Unlimited_add_cast = {{4{P_out1[39]}}, P_out1};
  assign Unlimited_add_cast_1 = {{12{Integrator_out1[31]}}, Integrator_out1};
  assign Unlimited_add_temp = Unlimited_add_cast + Unlimited_add_cast_1;
  assign Unlimited_out1 = ((Unlimited_add_temp[43] == 1'b0) && (Unlimited_add_temp[42:41] != 2'b00) ? 42'sh1FFFFFFFFFF :
              ((Unlimited_add_temp[43] == 1'b1) && (Unlimited_add_temp[42:41] != 2'b11) ? 42'sh20000000000 :
              $signed(Unlimited_add_temp[41:0])));
  assign Sat_UpperRelOp_out_1 = Unlimited_out1 > UpperLimit_out_1;

  assign OutputLimit_out1 = (Sat_UpperRelOp_out_1 == 1'b0 ? Sat_LowerSwitch_out :
              UpperLimit_out_1);

  assign OutputFormat_out1 = (((OutputLimit_out1[41] == 1'b0) && (OutputLimit_out1[40:39] != 2'b00)) || ((OutputLimit_out1[41] == 1'b0) && (OutputLimit_out1[39:15] == 25'sb0111111111111111111111111)) ? 25'sb0111111111111111111111111 :
              ((OutputLimit_out1[41] == 1'b1) && (OutputLimit_out1[40:39] != 2'b11) ? 25'sb1000000000000000000000000 :
              $signed(OutputLimit_out1[39:15]) + $signed({1'b0, OutputLimit_out1[14] & (OutputLimit_out1[15] | (|OutputLimit_out1[13:0]))})));
  assign OutputZero_out1 = 25'sb0000000000000000000000000;
  assign HardReset_out1 = (Hard_out1 == 1'b0 ? OutputFormat_out1 :
              OutputZero_out1);
  always_ff @(posedge clk)
    begin : iq_ref_A_hold_process
      if (init_reset == 1'b1) begin
        HardReset_out1_hold <= 25'sb0000000000000000000000000;
      end
      else begin
        if (enb_gated) begin
          HardReset_out1_hold <= HardReset_out1;
        end
      end
    end

  assign iq_ref_A = HardReset_out1_hold;

  always_ff @(posedge clk)
    begin : iq_unlimited_A_hold_process
      if (init_reset == 1'b1) begin
        Unlimited_out1_hold <= 42'sh00000000000;
      end
      else begin
        if (enb_gated) begin
          Unlimited_out1_hold <= Unlimited_out1;
        end
      end
    end

  assign iq_unlimited_A = Unlimited_out1_hold;

  always_ff @(posedge clk)
    begin : integrator_A_hold_process
      if (init_reset == 1'b1) begin
        Integrator_out1_hold <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_gated) begin
          Integrator_out1_hold <= Integrator_out1;
        end
      end
    end

  assign integrator_A = Integrator_out1_hold;

  assign Saturated_out1 = Unlimited_out1 != OutputLimit_out1;
  always_ff @(posedge clk)
    begin : saturation_active_hold_process
      if (init_reset == 1'b1) begin
        Saturated_out1_hold <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          Saturated_out1_hold <= Saturated_out1;
        end
      end
    end

  assign saturation_active = Saturated_out1_hold;

  always_ff @(posedge clk)
    begin : integrator_next_A_hold_process
      if (init_reset == 1'b1) begin
        IntReset_out1_hold <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_gated) begin
          IntReset_out1_hold <= IntReset_out1;
        end
      end
    end

  assign integrator_next_A = IntReset_out1_hold;

  always_ff @(posedge clk)
    begin : previous_excess_A_hold_process
      if (init_reset == 1'b1) begin
        PreviousExcess_out1_hold <= 40'sh0000000000;
      end
      else begin
        if (enb_gated) begin
          PreviousExcess_out1_hold <= PreviousExcess_out1;
        end
      end
    end

  assign previous_excess_A = PreviousExcess_out1_hold;

  always_ff @(posedge clk)
    begin : excess_next_A_hold_process
      if (init_reset == 1'b1) begin
        Excess_out1_hold <= 40'sh0000000000;
      end
      else begin
        if (enb_gated) begin
          Excess_out1_hold <= Excess_out1;
        end
      end
    end

  assign excess_next_A = Excess_out1_hold;

  always_ff @(posedge clk)
    begin : hard_reset_hold_process
      if (init_reset == 1'b1) begin
        Hard_out1_hold <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          Hard_out1_hold <= Hard_out1;
        end
      end
    end

  assign hard_reset = Hard_out1_hold;

  always_ff @(posedge clk)
    begin : int_reset_hold_process
      if (init_reset == 1'b1) begin
        Int_out1_hold <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          Int_out1_hold <= Int_out1;
        end
      end
    end

  assign int_reset = Int_out1_hold;

  always_ff @(posedge clk)
    begin : iq_limited_A_hold_process
      if (init_reset == 1'b1) begin
        OutputLimit_out1_hold <= 42'sh00000000000;
      end
      else begin
        if (enb_gated) begin
          OutputLimit_out1_hold <= OutputLimit_out1;
        end
      end
    end

  assign iq_limited_A = OutputLimit_out1_hold;

  always_ff @(posedge clk)
    begin : error_mmps_hold_process
      if (init_reset == 1'b1) begin
        Error_out1_hold <= 33'sh000000000;
      end
      else begin
        if (enb_gated) begin
          Error_out1_hold <= Error_out1;
        end
      end
    end

  assign error_mmps = Error_out1_hold;

  always_ff @(posedge clk)
    begin : P_A_hold_process
      if (init_reset == 1'b1) begin
        P_out1_hold <= 40'sh0000000000;
      end
      else begin
        if (enb_gated) begin
          P_out1_hold <= P_out1;
        end
      end
    end

  assign P_A = P_out1_hold;

  always_ff @(posedge clk)
    begin : KiTs_A_hold_process
      if (init_reset == 1'b1) begin
        KiTs_out1_hold <= 40'sh0000000000;
      end
      else begin
        if (enb_gated) begin
          KiTs_out1_hold <= KiTs_out1;
        end
      end
    end

  assign KiTs_A = KiTs_out1_hold;

  always_ff @(posedge clk)
    begin : AW_A_hold_process
      if (init_reset == 1'b1) begin
        AW_out1_hold <= 40'sh0000000000;
      end
      else begin
        if (enb_gated) begin
          AW_out1_hold <= AW_out1;
        end
      end
    end

  assign AW_A = AW_out1_hold;

endmodule  // PI

